In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'category': ['skirt', 'sweater', 'coat', 'jeans'],
    'quantity': [10, 15, 6, 11],                                     
    'price': [30000, 60000, 95000, 35000]
})

df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000

In [15]:
df['quantity']

0    10
1    15
2     6
3    11
Name: quantity, dtype: int64

In [16]:
type(df['quantity'])

pandas.Series

In [17]:
type(df)

pandas.DataFrame

In [18]:
df['quantity'].mean()

np.float64(10.5)

In [19]:
df['quantity'].sum()

np.int64(42)

In [20]:
df['quantity'].min()

np.int64(6)

In [21]:
df['quantity'] * df['price']

0    300000
1    900000
2    570000
3    385000
dtype: int64

In [23]:
two_dimensional_list = [
    ['skirt', 10, 30000],
    ['sweater', 15, 60000],
    ['coat', 6, 95000],
    ['jeans', 11, 35000]
]

two_dimensional_array = np.array(two_dimensional_list)

list_df = pd.DataFrame(two_dimensional_list)
array_df = pd.DataFrame(two_dimensional_array)

In [24]:
list_df

         0   1      2
0    skirt  10  30000
1  sweater  15  60000
2     coat   6  95000
3    jeans  11  35000

In [25]:
array_df

         0   1      2
0    skirt  10  30000
1  sweater  15  60000
2     coat   6  95000
3    jeans  11  35000

In [26]:
list_df = pd.DataFrame(two_dimensional_list, columns=['category', 'quantity', 'price'])
array_df = pd.DataFrame(two_dimensional_array, columns=['category', 'quantity', 'price'])

In [27]:
list_df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000

In [28]:
array_df

  category quantity  price
0    skirt       10  30000
1  sweater       15  60000
2     coat        6  95000
3    jeans       11  35000

In [30]:
dict_list = [
    {'category': 'skirt', 'quantity': 10, 'price': 30000},
    {'category': 'sweater', 'quantity': 15, 'price': 60000},
    {'category': 'coat', 'quantity': 6, 'price': 95000},
    {'category': 'jeans', 'quantity': 11, 'price': 35000}
]

dict_list_df = pd.DataFrame(dict_list)

dict_list_df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000