In [19]:
import pandas as pd

players_df = pd.read_csv('data/tottenham_2021.csv', index_col='name')

players_df

                   matches  minutes  goals  assists
name
Pierre Højbjerg         38     3420      2        4
Hugo Lloris             38     3420      0        0
Son Heung-Min           37     3114     17       10
Harry Kane              35     3082     23       14
Eric Dier               28     2520      0        0
Tanguy Ndombele         33     2091      3        2
Sergio Reguilón         27     2244      0        3
Toby Alderweireld       25     2240      1        0
Serge Aurier            19     1605      2        3
Davinson Sánchez        18     1486      0        0
Moussa Sissoko          25     1585      0        0
Lucas Moura             30     1411      3        4
Ben Davies              20     1346      0        1
Matt Doherty            17     1240      0        2
Steven Bergwijn         21     1208      1        3
Giovani Lo Celso        18      945      1        1
Gareth Bale             20      920     11        2
Harry Winks             15      861      0        0
Joe Rodon               12      733      0        0
Dele Alli               15      620      0        1
Japhet Tanganga          6      487      0        0
Érik Lamela             23      717      1        0
Carlos Vinícius          9      308      1        0
Dane Scarlett            1        1      0        0

In [20]:
players_df['minutes'].min()

np.int64(1)

In [21]:
players_df.loc['Son Heung-Min','goals']

np.int64(17)

In [22]:
players_df

                   matches  minutes  goals  assists
name
Pierre Højbjerg         38     3420      2        4
Hugo Lloris             38     3420      0        0
Son Heung-Min           37     3114     17       10
Harry Kane              35     3082     23       14
Eric Dier               28     2520      0        0
Tanguy Ndombele         33     2091      3        2
Sergio Reguilón         27     2244      0        3
Toby Alderweireld       25     2240      1        0
Serge Aurier            19     1605      2        3
Davinson Sánchez        18     1486      0        0
Moussa Sissoko          25     1585      0        0
Lucas Moura             30     1411      3        4
Ben Davies              20     1346      0        1
Matt Doherty            17     1240      0        2
Steven Bergwijn         21     1208      1        3
Giovani Lo Celso        18      945      1        1
Gareth Bale             20      920     11        2
Harry Winks             15      861      0        0
Joe Rodon               12      733      0        0
Dele Alli               15      620      0        1
Japhet Tanganga          6      487      0        0
Érik Lamela             23      717      1        0
Carlos Vinícius          9      308      1        0
Dane Scarlett            1        1      0        0

In [23]:
mask = players_df['goals'] >= 1
players_df[mask]

                   matches  minutes  goals  assists
name
Pierre Højbjerg         38     3420      2        4
Son Heung-Min           37     3114     17       10
Harry Kane              35     3082     23       14
Tanguy Ndombele         33     2091      3        2
Toby Alderweireld       25     2240      1        0
Serge Aurier            19     1605      2        3
Lucas Moura             30     1411      3        4
Steven Bergwijn         21     1208      1        3
Giovani Lo Celso        18      945      1        1
Gareth Bale             20      920     11        2
Érik Lamela             23      717      1        0
Carlos Vinícius          9      308      1        0

In [25]:
players_df = pd.read_csv('data/tottenham_2122.csv', index_col='name')

players_df

                        matches  minutes  goals  assists
name
Harry Kane                 37.0     3229     17        9
Dejan Kulusevski           18.0     1276      5        8
Steven Bergwijn            25.0      518      3        1
Pierre-Emile Højbjerg      36.0     3202      2        2
Lucas Moura                34.0     1770      2        6
Davinson Sánchez           23.0     1618      2        0
Matt Doherty               15.0      864      2        4
Sergio Reguilón            25.0     1929      2        3
Ben Davies                  NaN     2542      1        1
Tanguy NDombele Alvaro      9.0      490      1        1
Cristian Romero            22.0     1850      1        0
Emerson                    31.0     2296      1        1
Hugo Lloris                38.0     3420      0        0
Eric Dier                  35.0     3071      0        0
Harry Winks                19.0      896      0        1
Giovani Lo Celso            9.0      223      0        0
Rodrigo Bentancur          17.0     1376      0        4
Joe Rodon                   3.0       86      0        0
Ryan Sessegnon             15.0     1065      0        2
Oliver Skipp               18.0     1340      0        0
Bryan Gil Salvatierra       9.0       76      0        0
Japhet Tanganga            11.0      751      0        0
Dane Scarlett               1.0        2      0        0

In [26]:
players_df.loc['Son Heung-Min'] = [35,3051,23,7]
players_df.loc['Ben Davies','matches'] = 29
players_df['team'] = 'Tottenham'
players_df

                        matches  minutes  goals  assists       team
name
Harry Kane                 37.0     3229     17        9  Tottenham
Dejan Kulusevski           18.0     1276      5        8  Tottenham
Steven Bergwijn            25.0      518      3        1  Tottenham
Pierre-Emile Højbjerg      36.0     3202      2        2  Tottenham
Lucas Moura                34.0     1770      2        6  Tottenham
Davinson Sánchez           23.0     1618      2        0  Tottenham
Matt Doherty               15.0      864      2        4  Tottenham
Sergio Reguilón            25.0     1929      2        3  Tottenham
Ben Davies                 29.0     2542      1        1  Tottenham
Tanguy NDombele Alvaro      9.0      490      1        1  Tottenham
Cristian Romero            22.0     1850      1        0  Tottenham
Emerson                    31.0     2296      1        1  Tottenham
Hugo Lloris                38.0     3420      0        0  Tottenham
Eric Dier                  35.0     3071      0        0  Tottenham
Harry Winks                19.0      896      0        1  Tottenham
Giovani Lo Celso            9.0      223      0        0  Tottenham
Rodrigo Bentancur          17.0     1376      0        4  Tottenham
Joe Rodon                   3.0       86      0        0  Tottenham
Ryan Sessegnon             15.0     1065      0        2  Tottenham
Oliver Skipp               18.0     1340      0        0  Tottenham
Bryan Gil Salvatierra       9.0       76      0        0  Tottenham
Japhet Tanganga            11.0      751      0        0  Tottenham
Dane Scarlett               1.0        2      0        0  Tottenham
Son Heung-Min              35.0     3051     23        7  Tottenham