## 은행의 대출 심사 내역이 담겨있는 데이터 사용

In [28]:
import pandas as pd

In [29]:
loan_df = pd.read_csv('data/loan.csv')
loan_df

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [30]:
loan_df.head()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y

In [31]:
loan_df.tail()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [32]:
loan_df.shape  #row는 600개 컬럼은 7개

(600, 7)

In [33]:
loan_df.dtypes   # 컬럼별로 데이터 타입을 볼 수 있음

loan_id                     str
married_or_not              str
self_employed_or_not        str
applicant_income          int64
loan_amount             float64
property_area               str
loan_status                 str
dtype: object

In [34]:
loan_df.info()  # 결측값 정보

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_id               600 non-null    str
 1   married_or_not        600 non-null    str
 2   self_employed_or_not  568 non-null    str
 3   applicant_income      600 non-null    int64
 4   loan_amount           589 non-null    float64
 5   property_area         600 non-null    str
 6   loan_status           600 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 41.2 KB

In [35]:
loan_df.describe(include='all') # 숫자 데이터의 통계량을 요약해서 보여줌

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
count,600,600,568,600.000000,589.000000,600,600
unique,600,2,2,NaN,NaN,3,2
top,LP1003,Y,N,NaN,NaN,Suburb,Y
freq,1,390,488,NaN,NaN,228,408
mean,NaN,NaN,NaN,5412.161667,146.971307,NaN,NaN
std,NaN,NaN,NaN,6160.362669,85.756442,NaN,NaN
min,NaN,NaN,NaN,150.000000,9.200000,NaN,NaN
25%,NaN,NaN,NaN,2880.500000,100.700000,NaN,NaN
50%,NaN,NaN,NaN,3806.000000,128.000000,NaN,NaN
75%,NaN,NaN,NaN,5785.000000,168.300000,NaN,NaN
max,NaN,NaN,NaN,81000.000000,700.300000,NaN,NaN

In [36]:
loan_df

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [37]:
loan_df.sort_values(by='loan_amount') # 오름차순

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
555,LP2840,N,N,2378,9.2,City,N
13,LP1030,Y,N,1299,17.5,City,Y
91,LP1325,N,N,3620,25.0,Suburb,Y
125,LP1482,Y,Y,3459,25.3,Suburb,Y
542,LP2792,Y,N,5468,26.5,Suburb,Y
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [38]:
loan_df.sort_values(by='loan_amount',ascending=False) # 내림차순

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
163,LP1585,Y,N,51763,700.3,City,Y
122,LP1469,N,Y,20166,650.2,City,Y
548,LP2813,Y,Y,19484,600.4,Suburb,Y
147,LP1536,Y,N,39999,600.0,Suburb,Y
359,LP2191,Y,N,19730,570.1,Rural,N
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [39]:
loan_df.set_index('loan_id')

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.6,Rural,Y
LP2979,Y,N,4106,40.7,Rural,Y
LP2983,Y,N,8072,253.4,City,Y
LP2984,Y,N,7583,187.6,City,Y
LP2990,N,Y,4583,133.2,Suburb,N

In [40]:
loan_df = loan_df.set_index('loan_id')
loan_df

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.6,Rural,Y
LP2979,Y,N,4106,40.7,Rural,Y
LP2983,Y,N,8072,253.4,City,Y
LP2984,Y,N,7583,187.6,City,Y
LP2990,N,Y,4583,133.2,Suburb,N

In [ ]:
loan_df.columns    #컬럼들의 이름만 가져오기

Index(['married_or_not', 'self_employed_or_not', 'applicant_income',
       'loan_amount', 'property_area', 'loan_status'],
      dtype='str')

In [ ]:
# 컬럼 이름 변경 가능

loan_df.columns = ['married', 'self_employed', 'applicant_income','loan_amount', 'property_area', 'loan_status']
loan_df

,married,self_employed,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.6,Rural,Y
LP2979,Y,N,4106,40.7,Rural,Y
LP2983,Y,N,8072,253.4,City,Y
LP2984,Y,N,7583,187.6,City,Y
LP2990,N,Y,4583,133.2,Suburb,N

In [ ]:
new_columns = {'applicant_income': 'income', 'loan_amount': 'amount'}
loan_df.rename(columns=new_columns)  # colums이름 변경

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [47]:
loan_df = loan_df.rename(columns=new_columns)

- 각 컬럼의 데이터 타입 확인

In [49]:
loan_df.dtypes

married              str
self_employed        str
income             int64
amount           float64
property_area        str
loan_status          str
dtype: object

In [50]:
loan_df['income'].astype('float')

loan_id
LP1003    4583.0
LP1005    3000.0
LP1006    2583.0
LP1008    6000.0
LP1011    5417.0
           ...
LP2974    3232.0
LP2979    4106.0
LP2983    8072.0
LP2984    7583.0
LP2990    4583.0
Name: income, Length: 600, dtype: float64

In [51]:
loan_df.dtypes

married              str
self_employed        str
income             int64
amount           float64
property_area        str
loan_status          str
dtype: object

In [52]:
loan_df['income'] = loan_df['income'].astype('float')

In [53]:
loan_df.dtypes

married              str
self_employed        str
income           float64
amount           float64
property_area        str
loan_status          str
dtype: object

In [54]:
loan_df['amount'].dtypes

dtype('float64')

In [55]:
loan_df['amount'].describe()

count    589.000000
mean     146.971307
std       85.756442
min        9.200000
25%      100.700000
50%      128.000000
75%      168.300000
max      700.300000
Name: amount, dtype: float64

In [56]:
loan_df['self_employed'].dtypes

In [58]:
loan_df['self_employed'].describe()

count     568
unique      2
top         N
freq      488
Name: self_employed, dtype: object

In [59]:
loan_df['self_employed'].unique()

<ArrowStringArray>
['N', 'Y', nan]
Length: 3, dtype: str

In [ ]:
loan_df['self_employed'].value_counts()

self_employed
N    488
Y     80
Name: count, dtype: int64

In [61]:
loan_df['self_employed'].value_counts(dropna=False)

self_employed
N      488
Y       80
NaN     32
Name: count, dtype: int64

In [62]:
loan_df['self_employed'].value_counts(dropna=False,normalize=True)

self_employed
N      0.813333
Y      0.133333
NaN    0.053333
Name: proportion, dtype: float64

## 여러 개의 조건으로 불린 인덱싱하기

In [64]:
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.4         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.5          City           Y
LP1008        N             N  6000.0   141.4          City           Y
LP1011        Y             Y  5417.0   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.6         Rural           Y
LP2979        Y             N  4106.0    40.7         Rural           Y
LP2983        Y             N  8072.0   253.4          City           Y
LP2984        Y             N  7583.0   187.6          City           Y
LP2990        N             Y  4583.0   133.2        Suburb           N

[600 rows x 6 columns]

In [63]:
condition1 = loan_df['married'] == 'Y'

In [65]:
loan_df['income'].mean()

np.float64(5412.161666666667)

In [ ]:
condition2 = loan_df['income'] > loan_df['income'].mean()

In [74]:
loan_df[condition1 & condition2]

        married self_employed   income  amount property_area loan_status
loan_id
LP1011        Y             Y   5417.0   267.4          City           Y
LP1020        Y             N  12841.0   349.3        Suburb           N
LP1043        Y             N   7660.0   104.1          City           N
LP1046        Y             N   5955.0   315.5          City           Y
LP1066        Y             Y   9560.0   191.1        Suburb           Y
...         ...           ...      ...     ...           ...         ...
LP2948        Y             N   5780.0   192.9          City           Y
LP2953        Y             N   5703.0   128.5          City           Y
LP2959        Y             N  12000.0   497.0        Suburb           Y
LP2983        Y             N   8072.0   253.4          City           Y
LP2984        Y             N   7583.0   187.6          City           Y

[120 rows x 6 columns]

In [75]:
loan_df[condition1 | condition2]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.4         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.5          City           Y
LP1008        N             N  6000.0   141.4          City           Y
LP1011        Y             Y  5417.0   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N  3987.0   157.3         Rural           Y
LP2974        Y             N  3232.0   108.6         Rural           Y
LP2979        Y             N  4106.0    40.7         Rural           Y
LP2983        Y             N  8072.0   253.4          City           Y
LP2984        Y             N  7583.0   187.6          City           Y

[442 rows x 6 columns]

In [76]:
loan_df[(loan_df['married'] == 'Y') | (loan_df['income'] > loan_df['income'].mean())]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.4         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.5          City           Y
LP1008        N             N  6000.0   141.4          City           Y
LP1011        Y             Y  5417.0   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N  3987.0   157.3         Rural           Y
LP2974        Y             N  3232.0   108.6         Rural           Y
LP2979        Y             N  4106.0    40.7         Rural           Y
LP2983        Y             N  8072.0   253.4          City           Y
LP2984        Y             N  7583.0   187.6          City           Y

[442 rows x 6 columns]

In [ ]:
# 결혼을 했거나, 수입이 전체 평균보다 크고, 부동산이 도시에 있지 않다. 
# loan_df[(loan_df['property_area'] != 'City') & (loan_df['income'] > loan_df['income'].mean()) | (loan_df['married'] == 'Y')]

condition3 = loan_df['property_area'] == 'City'
loan_df[condition1 | (condition2 & ~condition3)]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.4         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.5          City           Y
LP1011        Y             Y  5417.0   267.4          City           Y
LP1013        Y             N  2333.0    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N  3987.0   157.3         Rural           Y
LP2974        Y             N  3232.0   108.6         Rural           Y
LP2979        Y             N  4106.0    40.7         Rural           Y
LP2983        Y             N  8072.0   253.4          City           Y
LP2984        Y             N  7583.0   187.6          City           Y

[426 rows x 6 columns]

: