# airbnb 숙소 데이터 사용

## 결측값 찾기

In [32]:
import pandas as pd

airbnb_df = pd.read_csv('data/airbnb.csv')
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [33]:
airbnb_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             713 non-null    str
 1   state          713 non-null    str
 2   guests         713 non-null    int64
 3   beds           713 non-null    int64
 4   property_type  713 non-null    str
 5   rating         700 non-null    float64
 6   n_reviews      713 non-null    int64
 7   location       713 non-null    str
 8   price          713 non-null    int64
dtypes: float64(1), int64(4), str(4)
memory usage: 83.4 KB

In [34]:
airbnb_df.isna()   # 결측값 여부

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
708,False,False,False,False,False,False,False,False,False
709,False,False,False,False,False,False,False,False,False
710,False,False,False,False,False,False,False,False,False
711,False,False,False,False,False,False,False,False,False
712,False,False,False,False,False,False,False,False,False

In [35]:
airbnb_df.isna().sum()  # rating에 결측값이 13개 있음

id                0
state             0
guests            0
beds              0
property_type     0
rating           13
n_reviews         0
location          0
price             0
dtype: int64

In [36]:
airbnb_df.isna().any(axis=1)  #각 row별로 결측값의 존재 여부를 알 수 있음

0      False
1       True
2      False
3      False
4      False
       ...
708    False
709    False
710    False
711    False
712    False
Length: 713, dtype: bool

In [37]:
airbnb_df[airbnb_df.isna().any(axis=1)]  # 결측값이 있는 데이터만 뽑아서

,id,state,guests,beds,property_type,rating,n_reviews,location,price
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
127,MB7199,Illinois,2,1,Apartment,NaN,0,"Rogers Park, Chicago.",74
189,DE6323,illinois,2,1,Condominium,NaN,0,"South Loop/Printers Row, Chicago.",79
206,ME5527,ILLINOIS,2,1,House,NaN,0,"Garfield Park, Chicago.",52
272,RM9271,illinois,2,1,Apartment,NaN,0,"Lincoln Park, Chicago.",64
275,TA9777,California,2,1,Condominium,NaN,0,"Pacific Heights, San Francisco.",115
366,LP6045,ILLINOIS,2,1,Apartment,NaN,0,"Loop, Chicago.",115
534,DC4208,ILLINOIS,5,3,House,NaN,0,"Little Italy/UIC, Chicago.",100
546,IE7576,illinois,1,1,House,NaN,0,"South Chicago, Chicago.",50
552,DY9962,California,1,1,Condominium,NaN,0,"Valley Village, Los Angeles.",85
586,UW2000,California,8,1,Other,NaN,0,"South LA, Los Angeles.",169
594,VM7350,ILLINOIS,2,1,Apartment,NaN,0,"Little Italy/UIC, Chicago.",46
632,NH9205,California,4,2,Apartment,NaN,0,"El Segundo, Los Angeles.",100

In [38]:
airbnb_df.dropna()  # 결측값 삭제

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
5,PP4626,California,2,1,Apartment,92.0,211,"Western Addition/NOPA, San Francisco.",129
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [39]:
airbnb_df['rating'].mean().round(0)

np.float64(95.0)

In [40]:
airbnb_mean = airbnb_df['rating'].mean().round(0)

In [41]:
airbnb_df['rating'].fillna(airbnb_mean)

0       96.0
1       95.0
2      100.0
3       75.0
4       88.0
       ...
708     97.0
709     93.0
710     93.0
711     80.0
712     96.0
Name: rating, Length: 713, dtype: float64

In [42]:
# 결측값이 있던 부분에 잘 채워졌는지 mask를 사용해서 다시 확인
mask = airbnb_df['rating'].isna()
airbnb_df['rating'].fillna(airbnb_mean)[mask]

1      95.0
127    95.0
189    95.0
206    95.0
272    95.0
275    95.0
366    95.0
534    95.0
546    95.0
552    95.0
586    95.0
594    95.0
632    95.0
Name: rating, dtype: float64

In [43]:
airbnb_df['rating'] = airbnb_df['rating'].fillna(airbnb_mean)

In [44]:
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,95.0,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [45]:
airbnb_df.isna().sum()

id               0
state            0
guests           0
beds             0
property_type    0
rating           0
n_reviews        0
location         0
price            0
dtype: int64

## 중복값 찾기

In [46]:
airbnb_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
708    False
709    False
710    False
711    False
712    False
Length: 713, dtype: bool

In [47]:
airbnb_df.duplicated().sum()

np.int64(2)

In [48]:
airbnb_df[airbnb_df.duplicated()]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124

In [49]:
airbnb_df[airbnb_df.duplicated(subset='id')]   # keep='first'

,id,state,guests,beds,property_type,rating,n_reviews,location,price
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
452,LN3479,California,2,2,Apartment,99.0,25,"East Hollywood, Los Angeles.",91
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119

In [50]:
airbnb_df[airbnb_df.duplicated(subset='id',keep=False)]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
6,LN3479,California,2,2,Apartment,96.0,15,"East Hollywood, Los Angeles.",88
201,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
273,QO8555,California,7,4,House,85.0,3,"Excelsior, San Francisco.",199
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
452,LN3479,California,2,2,Apartment,99.0,25,"East Hollywood, Los Angeles.",91
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
541,BZ3596,Illinois,2,1,Apartment,91.0,28,"Lakeview, Chicago.",119
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119

### 중복값 처리하기

In [51]:
airbnb_df.duplicated().sum()

np.int64(2)

In [52]:
airbnb_df.drop_duplicates()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,95.0,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [53]:
airbnb_df.drop_duplicates(subset='id')

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,95.0,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [54]:
airbnb_df = airbnb_df.drop_duplicates(subset='id',keep='last' )

In [55]:
airbnb_df.duplicated(subset='id').sum()

np.int64(0)

## 이상점 찾기 (Outlier)

In [57]:
q1 = airbnb_df['price'].quantile(0.25)
q3 = airbnb_df['price'].quantile(0.75)

In [58]:
iqr = q3 - q1

In [59]:
lower_limit = q1 - 1.5*iqr
upper_limit = q3 + 1.5*iqr

In [60]:
airbnb_df['price'] < lower_limit

0      False
1      False
2      False
3      False
4      False
       ...
708    False
709    False
710    False
711    False
712    False
Name: price, Length: 707, dtype: bool

In [61]:
airbnb_df[airbnb_df['price'] < lower_limit]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
13,HB7516,Illinois,1,1,Apartment,94.0,56,"Little Italy/UIC, Chicago.",14
43,IT4655,California,2,8,Hostel,91.0,27,"Westlake, Los Angeles.",14

In [62]:
airbnb_df[airbnb_df['price'] > upper_limit]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
91,FG7538,California,6,3,House,100.0,6,"Marina, San Francisco.",1800
442,ZL3688,California,16,8,Villa,92.0,7,"Malibu, Los Angeles.",1794

In [64]:
airbnb_df[(airbnb_df['price'] < lower_limit )| (airbnb_df['price'] > upper_limit)]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
13,HB7516,Illinois,1,1,Apartment,94.0,56,"Little Italy/UIC, Chicago.",14
43,IT4655,California,2,8,Hostel,91.0,27,"Westlake, Los Angeles.",14
91,FG7538,California,6,3,House,100.0,6,"Marina, San Francisco.",1800
442,ZL3688,California,16,8,Villa,92.0,7,"Malibu, Los Angeles.",1794

### 이상점 처리하기

In [ ]:
# 정상범위
condition1 = airbnb_df['price'] >= lower_limit
condition2 = airbnb_df['price'] <= upper_limit

In [66]:
airbnb_df[condition1 & condition2]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,95.0,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115