In [4]:
import pandas as pd

airbnb_df = pd.read_csv('data/airbnb.csv')
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [5]:
airbnb_df['state'].unique()

<ArrowStringArray>
[     'Illinois', 'MASSACHUSETTS',      'ILLINOIS',    'california',
 'massachusetts',    'California', 'Massachusetts',    'CALIFORNIA',
      'illinois']
Length: 9, dtype: str

In [6]:
airbnb_df['state'].lower()

AttributeError: 'Series' object has no attribute 'lower'

In [7]:
airbnb_df['state'].str.lower()

0           illinois
1      massachusetts
2           illinois
3         california
4      massachusetts
           ...
708       california
709       california
710       california
711         illinois
712    massachusetts
Name: state, Length: 713, dtype: str

In [8]:
airbnb_df['state'].str.upper()

0           ILLINOIS
1      MASSACHUSETTS
2           ILLINOIS
3         CALIFORNIA
4      MASSACHUSETTS
           ...
708       CALIFORNIA
709       CALIFORNIA
710       CALIFORNIA
711         ILLINOIS
712    MASSACHUSETTS
Name: state, Length: 713, dtype: str

In [9]:
airbnb_df['state'].str.capitalize()

0           Illinois
1      Massachusetts
2           Illinois
3         California
4      Massachusetts
           ...
708       California
709       California
710       California
711         Illinois
712    Massachusetts
Name: state, Length: 713, dtype: str

In [10]:
airbnb_df['state'] = airbnb_df['state'].str.capitalize()
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,California,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,Illinois,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [11]:
airbnb_df['location'].str.split(',')

0               [Avondale,  Chicago.]
1               [South End,  Boston.]
2               [Avondale,  Chicago.]
3             [SoMa,  San Francisco.]
4            [West Roxbury,  Boston.]
                    ...
708           [Venice,  Los Angeles.]
709     [Mid-Wilshire,  Los Angeles.]
710    [Redondo Beach,  Los Angeles.]
711             [Lakeview,  Chicago.]
712           [East Boston,  Boston.]
Name: location, Length: 713, dtype: object

In [12]:
airbnb_df['location'].str.split(',').str[0]

0           Avondale
1          South End
2           Avondale
3               SoMa
4       West Roxbury
           ...
708           Venice
709     Mid-Wilshire
710    Redondo Beach
711         Lakeview
712      East Boston
Name: location, Length: 713, dtype: object

In [13]:
airbnb_df['neighborhood'] = airbnb_df['location'].str.split(',').str[0]
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price,neighborhood
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48,Avondale
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115,South End
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150,Avondale
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125,SoMa
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64,West Roxbury
...,...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150,Venice
709,ZR5298,California,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100,Mid-Wilshire
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100,Redondo Beach
711,EE8333,Illinois,2,1,House,80.0,15,"Lakeview, Chicago.",115,Lakeview
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115,East Boston

In [14]:
airbnb_df['city'] = airbnb_df['location'].str.split(',').str[1]
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48,Avondale,Chicago.
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115,South End,Boston.
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150,Avondale,Chicago.
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125,SoMa,San Francisco.
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64,West Roxbury,Boston.
...,...,...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150,Venice,Los Angeles.
709,ZR5298,California,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100,Mid-Wilshire,Los Angeles.
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100,Redondo Beach,Los Angeles.
711,EE8333,Illinois,2,1,House,80.0,15,"Lakeview, Chicago.",115,Lakeview,Chicago.
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115,East Boston,Boston.

In [15]:
airbnb_df = airbnb_df.drop(columns='location')  #('location',axis=1) 
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago.
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston.
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago.
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco.
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston.
...,...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,150,Venice,Los Angeles.
709,ZR5298,California,4,2,Apartment,93.0,3,100,Mid-Wilshire,Los Angeles.
710,XZ5531,California,2,1,Bungalow,93.0,3,100,Redondo Beach,Los Angeles.
711,EE8333,Illinois,2,1,House,80.0,15,115,Lakeview,Chicago.
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,115,East Boston,Boston.

### 불필요한 문자 제거하기

In [16]:
airbnb_df[airbnb_df['city'] == 'Boston']

Empty DataFrame
Columns: [id, state, guests, beds, property_type, rating, n_reviews, price, neighborhood, city]
Index: []

In [18]:
airbnb_df['city'].unique()

array([' Chicago.', ' Boston.', ' San Francisco.', ' Los Angeles.'],
      dtype=object)

In [20]:
airbnb_df['city'] = airbnb_df['city'].str.strip()

In [21]:
airbnb_df['city'].str.replace('.', '', regex=False)

0            Chicago
1             Boston
2            Chicago
3      San Francisco
4             Boston
           ...
708      Los Angeles
709      Los Angeles
710      Los Angeles
711          Chicago
712           Boston
Name: city, Length: 713, dtype: object

In [23]:
airbnb_df['city'] = airbnb_df['city'].str.replace('.', '', regex=False)

In [24]:
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston
...,...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,150,Venice,Los Angeles
709,ZR5298,California,4,2,Apartment,93.0,3,100,Mid-Wilshire,Los Angeles
710,XZ5531,California,2,1,Bungalow,93.0,3,100,Redondo Beach,Los Angeles
711,EE8333,Illinois,2,1,House,80.0,15,115,Lakeview,Chicago
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,115,East Boston,Boston