## 새로운 값 계산하기

In [1]:
import pandas as pd

patient_df = pd.read_csv('data/patient.csv')
patient_df

     age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0     50    Male      385          140    1.75    78.0   41     37        Y
1     37  Female       67          214    1.63    65.8   42     34        N
2     43  Female      100          160    1.63    63.5   40     37        N
3     32  Female       90          176    1.60   114.3   58     45        N
4     20    Male       71          164    1.83    65.8   36     29        N
..   ...     ...      ...          ...     ...     ...  ...    ...      ...
343   40    Male       87          218    1.85    90.7   41     38        N
344   66    Male      174          188    1.73    95.3   48     45        N
345   31  Female       69          183    1.68    86.2   47     41        N
346   44    Male       84          202    1.73    71.2   37     33        N
347   40  Female       85          169    1.65    81.6   44     40        N

[348 rows x 9 columns]

In [2]:
patient_df['waist'] / patient_df['hip']

0      0.902439
1      0.809524
2      0.925000
3      0.775862
4      0.805556
         ...
343    0.926829
344    0.937500
345    0.872340
346    0.891892
347    0.909091
Length: 348, dtype: float64

In [3]:
round(patient_df['waist'] / patient_df['hip'],2)

0      0.90
1      0.81
2      0.92
3      0.78
4      0.81
       ...
343    0.93
344    0.94
345    0.87
346    0.89
347    0.91
Length: 348, dtype: float64

In [5]:
patient_df['waist_hip_ratio'] = round(patient_df['waist'] / patient_df['hip'],2)
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,1.75,78.0,41,37,Y,0.90
1,37,Female,67,214,1.63,65.8,42,34,N,0.81
2,43,Female,100,160,1.63,63.5,40,37,N,0.92
3,32,Female,90,176,1.60,114.3,58,45,N,0.78
4,20,Male,71,164,1.83,65.8,36,29,N,0.81
...,...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,1.85,90.7,41,38,N,0.93
344,66,Male,174,188,1.73,95.3,48,45,N,0.94
345,31,Female,69,183,1.68,86.2,47,41,N,0.87
346,44,Male,84,202,1.73,71.2,37,33,N,0.89
347,40,Female,85,169,1.65,81.6,44,40,N,0.91

## 정규화
- 모든 값을 0과 1사이 값으로 바꿔줌  
 -> 데이터의 범위를 확실하게 통일하고 싶을 때 사용한다.

In [6]:
# 정규화 식 : 기본값 - 최소값 / 최댓값 - 최소값

(patient_df['height'] - patient_df['height'].min()) / \
(patient_df['height'].max() - patient_df['height'].min() )

0      0.704918
1      0.508197
2      0.508197
3      0.459016
4      0.836066
         ...
343    0.868852
344    0.672131
345    0.590164
346    0.672131
347    0.540984
Name: height, Length: 348, dtype: float64

In [7]:
patient_df['height'] = (patient_df['height'] - patient_df['height'].min()) / \
                       (patient_df['height'].max() - patient_df['height'].min() )

In [8]:
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,0.704918,78.0,41,37,Y,0.90
1,37,Female,67,214,0.508197,65.8,42,34,N,0.81
2,43,Female,100,160,0.508197,63.5,40,37,N,0.92
3,32,Female,90,176,0.459016,114.3,58,45,N,0.78
4,20,Male,71,164,0.836066,65.8,36,29,N,0.81
...,...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,0.868852,90.7,41,38,N,0.93
344,66,Male,174,188,0.672131,95.3,48,45,N,0.94
345,31,Female,69,183,0.590164,86.2,47,41,N,0.87
346,44,Male,84,202,0.672131,71.2,37,33,N,0.89
347,40,Female,85,169,0.540984,81.6,44,40,N,0.91

In [9]:
patient_df['height'].describe()

count    348.000000
mean       0.590588
std        0.163932
min        0.000000
25%        0.459016
50%        0.590164
75%        0.704918
max        1.000000
Name: height, dtype: float64

## 표준화
 - 평균은 0 표준편차는 1로 맞춰줌  
  -> 각 데이터가 평균에서 얼만큼 떨어져 있는지 비교

In [ ]:
(patient_df['height'] - patient_df['height'].mean()) / patient_df['height'].std()

0      0.697426
1     -0.502595
2     -0.502595
3     -0.802600
4      1.497440
         ...
343    1.697444
344    0.497423
345   -0.002586
346    0.497423
347   -0.302592
Name: height, Length: 348, dtype: float64

In [13]:
patient_df['height'] = (patient_df['height'] - patient_df['height'].mean()) / \
                        patient_df['height'].std()

In [14]:
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,0.697426,78.0,41,37,Y,0.90
1,37,Female,67,214,-0.502595,65.8,42,34,N,0.81
2,43,Female,100,160,-0.502595,63.5,40,37,N,0.92
3,32,Female,90,176,-0.802600,114.3,58,45,N,0.78
4,20,Male,71,164,1.497440,65.8,36,29,N,0.81
...,...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,1.697444,90.7,41,38,N,0.93
344,66,Male,174,188,0.497423,95.3,48,45,N,0.94
345,31,Female,69,183,-0.002586,86.2,47,41,N,0.87
346,44,Male,84,202,0.497423,71.2,37,33,N,0.89
347,40,Female,85,169,-0.302592,81.6,44,40,N,0.91

In [15]:
patient_df['height'].describe()

count    3.480000e+02
mean    -5.104474e-18
std      1.000000e+00
min     -3.602650e+00
25%     -8.026005e-01
50%     -2.586253e-03
75%      6.974262e-01
max      2.497458e+00
Name: height, dtype: float64