# 어떤 쇼핑몰의 주문 정보가 들어 있는 데이터

## 날짜와 시간을 위한 데이터 타입 설정하기

In [246]:
import pandas as pd

order_df = pd.read_csv('data/order.csv')
order_df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaN,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [247]:
order_df.dtypes

order_time                         str
category                           str
product_name                       str
price                          float64
quantity                         int64
sales                          float64
days_for_shipping(expected)      int64
shipping_time                      str
dtype: object

In [248]:
pd.to_datetime(order_df['order_time'])

0       2015-01-01 04:54:00
1                       NaT
2       2015-01-01 02:27:00
3       2015-01-01 19:58:00
4       2015-01-01 03:51:00
                ...
18045   2018-01-31 10:20:00
18046   2018-01-31 21:53:00
18047   2018-01-31 17:20:00
18048   2018-01-31 12:26:00
18049   2018-01-31 16:59:00
Name: order_time, Length: 18050, dtype: datetime64[us]

In [249]:
order_df['order_time'] = pd.to_datetime(order_df['order_time'])
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'])

In [250]:
order_df.dtypes

order_time                     datetime64[us]
category                                  str
product_name                              str
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[us]
dtype: object

In [251]:
#처음에 불러올 때 datetime으로 불러오는 방법
order_df = pd.read_csv('data/order.csv', parse_dates=['order_time','shipping_time'])

In [252]:
order_df.dtypes

order_time                     datetime64[us]
category                                  str
product_name                              str
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[us]
dtype: object

In [253]:
order_df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [254]:
order_df.isna().sum()

order_time                     1
category                       0
product_name                   0
price                          0
quantity                       0
sales                          0
days_for_shipping(expected)    0
shipping_time                  0
dtype: int64

In [255]:
order_df['order_time'].dt.date

0        2015-01-01
1               NaT
2        2015-01-01
3        2015-01-01
4        2015-01-01
            ...
18045    2018-01-31
18046    2018-01-31
18047    2018-01-31
18048    2018-01-31
18049    2018-01-31
Name: order_time, Length: 18050, dtype: object

In [256]:
order_df['order_time'].dt.year

0        2015.0
1           NaN
2        2015.0
3        2015.0
4        2015.0
          ...
18045    2018.0
18046    2018.0
18047    2018.0
18048    2018.0
18049    2018.0
Name: order_time, Length: 18050, dtype: float64

In [257]:
order_df['order_time'].dt.month

0        1.0
1        NaN
2        1.0
3        1.0
4        1.0
        ...
18045    1.0
18046    1.0
18047    1.0
18048    1.0
18049    1.0
Name: order_time, Length: 18050, dtype: float64

In [258]:
order_df['order_time'].dt.day

0         1.0
1         NaN
2         1.0
3         1.0
4         1.0
         ...
18045    31.0
18046    31.0
18047    31.0
18048    31.0
18049    31.0
Name: order_time, Length: 18050, dtype: float64

In [259]:
order_df['order_time'].dt.dayofweek

0        3.0
1        NaN
2        3.0
3        3.0
4        3.0
        ...
18045    2.0
18046    2.0
18047    2.0
18048    2.0
18049    2.0
Name: order_time, Length: 18050, dtype: float64

In [260]:
order_df = pd.read_csv('data/order1.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015/01/20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015/01/26 15:42:00
1,2015/02/07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015/02/09 12:33:00
2,2015/02/08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015/02/10 10:29:00
3,2015/02/24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015/03/02 16:14:00
4,2015/03/09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015/03/12 14:59:00

In [261]:
order_df.dtypes

order_time                         str
category                           str
product_name                       str
price                          float64
quantity                         int64
sales                          float64
days_for_shipping(expected)      int64
shipping_time                      str
dtype: object

In [262]:
order_df = pd.read_csv('data/order1.csv', parse_dates=['order_time', 'shipping_time'])
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00
1,2015-02-07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00

In [263]:
order_df.dtypes

order_time                     datetime64[us]
category                                  str
product_name                              str
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[us]
dtype: object

In [264]:
# 다른형식의 데이터 (미국형식 날짜)
order_df = pd.read_csv('data/order2.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,01/20/2015 09:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,01/26/2015 03:42:00
1,02/07/2015 10:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,02/09/2015 12:33:00
2,02/08/2015 01:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,02/10/2015 10:29:00
3,02/24/2015 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,03/02/2015 04:14:00
4,03/09/2015 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,03/12/2015 02:59:00

In [265]:
order_df = pd.read_csv('data/order2.csv', parse_dates=['order_time', 'shipping_time'])
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 09:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 03:42:00
1,2015-02-07 10:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 01:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 04:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 02:59:00

In [266]:
# 유럽형식
order_df = pd.read_csv('data/order3.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,20/01/2015 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,26/01/2015 15:42:00
1,07/02/2015 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,09/02/2015 12:33:00
2,08/02/2015 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,10/02/2015 10:29:00
3,24/02/2015 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,02/03/2015 16:14:00
4,09/03/2015 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,12/03/2015 14:59:00

In [267]:
# 이런 형식의 데이터를 불러올 때에는 dayfirst라는 파라미터를 True로 설정
# 이건 말 그대로 일자 값이 앞에 온다는 것을 의미 원래 기본값은 False로 되어 있어서,
# 따로 설정해 주지 않으면 월/일/연도 순서로 값을 인식
# 물론 따로 이 파라미터를 설정하지 않아도 20/01/2015 이런 식으로 
# 가장 앞에 있는 값이 월이 아니라 일이라는 것이 명확하면 pandas가 알아서 
# 일/월/연도 형식으로 판단하여 데이터를 불러옴. (20이라는 월은 존재하지 않기 때문)
# 하지만, 10/01/2015처럼 월/일/연도인지, 일/월/연도인지 명확하지 않은 경우도 많기 때문에 
# 따로 파라미터 값을 명확하게 설정해 주는 것이 좋음.


order_df = pd.read_csv('data/order3.csv', parse_dates=['order_time', 'shipping_time'], dayfirst=True)
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00
1,2015-02-07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00

## 데이터 타입을 변경할 때 형식 지정하기

In [268]:
# 년도가 2자리일 때 
order_df = pd.read_csv('data/order4.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,15/01/20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,15/01/26 15:42:00
1,15/02/07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,15/02/09 12:33:00
2,15/02/08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,15/02/10 10:29:00
3,15/02/24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,15/03/02 16:14:00
4,15/03/09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,15/03/12 14:59:00

In [269]:
order_df['order_time'] = pd.to_datetime(order_df['order_time'], yearfirst=True)
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'], yearfirst=True)

order_df.head()

C:\Users\SH\AppData\Local\Temp\ipykernel_13436\2395199552.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  order_df['order_time'] = pd.to_datetime(order_df['order_time'], yearfirst=True)
C:\Users\SH\AppData\Local\Temp\ipykernel_13436\2395199552.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'], yearfirst=True)

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00
1,2015-02-07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00

In [270]:
order_df = pd.read_csv('data/order5.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015년 01월 20일 21시 52분 00초,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015년 01월 26일 15시 42분 00초
1,2015년 02월 07일 22시 53분 00초,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015년 02월 09일 12시 33분 00초
2,2015년 02월 08일 13시 15분 00초,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015년 02월 10일 10시 29분 00초
3,2015년 02월 24일 03시 25분 00초,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015년 03월 02일 16시 14분 00초
4,2015년 03월 09일 03시 56분 00초,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015년 03월 12일 14시 59분 00초

In [271]:
order_df['order_time'] = pd.to_datetime(order_df['order_time'], format='%Y년 %m월 %d일 %H시 %M분 %S초')
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'], format='%Y년 %m월 %d일 %H시 %M분 %S초')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00
1,2015-02-07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00

## datetime을 원하는 형태로 바꿔서 표현하기

 반대로 datetime 값을 원하는 형태의 문자열로 바꿔서 표현하는 것도 가능  
예를 들어 2017-10-31 16:37:00이라는 값을 -> 31 October 2017, 04:37PM

In [272]:
order_df['order_time'] = order_df['order_time'].dt.strftime('%d %b %Y, %I:%M %p')
order_df['shipping_time'] = order_df['shipping_time'].dt.strftime('%d %b %Y, %I:%M %p')

order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,"20 Jan 2015, 09:52 PM",Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,"26 Jan 2015, 03:42 PM"
1,"07 Feb 2015, 10:53 PM",Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,"09 Feb 2015, 12:33 PM"
2,"08 Feb 2015, 01:15 PM",Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,"10 Feb 2015, 10:29 AM"
3,"24 Feb 2015, 03:25 AM",Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,"02 Mar 2015, 04:14 PM"
4,"09 Mar 2015, 03:56 AM",Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,"12 Mar 2015, 02:59 PM"

## 시간대 설정하기

In [273]:
order_df = pd.read_csv('data/order1.csv', parse_dates=['order_time', 'shipping_time'])
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-20 21:52:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00
1,2015-02-07 22:53:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00
2,2015-02-08 13:15:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00
3,2015-02-24 03:25:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00
4,2015-03-09 03:56:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00

In [274]:
order_df['order_time'].dt.tz_localize('Asia/Seoul')

0    2015-01-20 21:52:00+09:00
1    2015-02-07 22:53:00+09:00
2    2015-02-08 13:15:00+09:00
3    2015-02-24 03:25:00+09:00
4    2015-03-09 03:56:00+09:00
                ...
95   2017-09-13 21:23:00+09:00
96   2017-10-11 14:20:00+09:00
97   2017-10-19 15:23:00+09:00
98   2018-01-01 04:04:00+09:00
99   2018-01-18 15:47:00+09:00
Name: order_time, Length: 100, dtype: datetime64[us, Asia/Seoul]

In [275]:
order_df['order_time'] = order_df['order_time'].dt.tz_localize('Asia/Seoul')
order_df['shipping_time'] = order_df['shipping_time'].dt.tz_localize('Asia/Seoul')

In [276]:
order_df['order_time'].dt.tz_convert('America/New_York')

0    2015-01-20 07:52:00-05:00
1    2015-02-07 08:53:00-05:00
2    2015-02-07 23:15:00-05:00
3    2015-02-23 13:25:00-05:00
4    2015-03-08 14:56:00-04:00
                ...
95   2017-09-13 08:23:00-04:00
96   2017-10-11 01:20:00-04:00
97   2017-10-19 02:23:00-04:00
98   2017-12-31 14:04:00-05:00
99   2018-01-18 01:47:00-05:00
Name: order_time, Length: 100, dtype: datetime64[us, America/New_York]

In [277]:
import pytz

for tz in pytz.all_timezones:
    print(tz)

Africa/Abidjan
Africa/Accra
Africa/Addis_Ababa
Africa/Algiers
Africa/Asmara
Africa/Asmera
Africa/Bamako
Africa/Bangui
Africa/Banjul
Africa/Bissau
Africa/Blantyre
Africa/Brazzaville
Africa/Bujumbura
Africa/Cairo
Africa/Casablanca
Africa/Ceuta
Africa/Conakry
Africa/Dakar
Africa/Dar_es_Salaam
Africa/Djibouti
Africa/Douala
Africa/El_Aaiun
Africa/Freetown
Africa/Gaborone
Africa/Harare
Africa/Johannesburg
Africa/Juba
Africa/Kampala
Africa/Khartoum
Africa/Kigali
Africa/Kinshasa
Africa/Lagos
Africa/Libreville
Africa/Lome
Africa/Luanda
Africa/Lubumbashi
Africa/Lusaka
Africa/Malabo
Africa/Maputo
Africa/Maseru
Africa/Mbabane
Africa/Mogadishu
Africa/Monrovia
Africa/Nairobi
Africa/Ndjamena
Africa/Niamey
Africa/Nouakchott
Africa/Ouagadougou
Africa/Porto-Novo
Africa/Sao_Tome
Africa/Timbuktu
Africa/Tripoli
Africa/Tunis
Africa/Windhoek
America/Adak
America/Anchorage
America/Anguilla
America/Antigua
America/Araguaina
America/Argentina/Buenos_Aires
America/Argentina/Catamarca
America/Argentina/ComodRivadavia
America/Argentina/Cordoba
America/Argentina/Jujuy
America/Argentina/La_Rioja
America/Argentina/Mendoza
America/Argentina/Rio_Gallegos
America/Argentina/Salta
America/Argentina/San_Juan
America/Argentina/San_Luis
America/Argentina/Tucuman
America/Argentina/Ushuaia
America/Aruba
America/Asuncion
America/Atikokan
America/Atka
America/Bahia
America/Bahia_Banderas
America/Barbados
America/Belem
America/Belize
America/Blanc-Sablon
America/Boa_Vista
America/Bogota
America/Boise
America/Buenos_Aires
America/Cambridge_Bay
America/Campo_Grande
America/Cancun
America/Caracas
America/Catamarca
America/Cayenne
America/Cayman
America/Chicago
America/Chihuahua
America/Ciudad_Juarez
America/Coral_Harbour
America/Cordoba
America/Costa_Rica
America/Coyhaique
America/Creston
America/Cuiaba
America/Curacao
America/Danmarkshavn
America/Dawson
America/Dawson_Creek
America/Denver
America/Detroit
America/Dominica
America/Edmonton
America/Eirunepe
America/El_Salvador
America/Ensenada
America/Fort_Nelson
America/Fort_Wayne
America/Fortaleza
America/Glace_Bay
America/Godthab
America/Goose_Bay
America/Grand_Turk
America/Grenada
America/Guadeloupe
America/Guatemala
America/Guayaquil
America/Guyana
America/Halifax
America/Havana
America/Hermosillo
America/Indiana/Indianapolis
America/Indiana/Knox
America/Indiana/Marengo
America/Indiana/Petersburg
America/Indiana/Tell_City
America/Indiana/Vevay
America/Indiana/Vincennes
America/Indiana/Winamac
America/Indianapolis
America/Inuvik
America/Iqaluit
America/Jamaica
America/Jujuy
America/Juneau
America/Kentucky/Louisville
America/Kentucky/Monticello
America/Knox_IN
America/Kralendijk
America/La_Paz
America/Lima
America/Los_Angeles
America/Louisville
America/Lower_Princes
America/Maceio
America/Managua
America/Manaus
America/Marigot
America/Martinique
America/Matamoros
America/Mazatlan
America/Mendoza
America/Menominee
America/Merida
America/Metlakatla
America/Mexico_City
America/Miquelon
America/Moncton
America/Monterrey
America/Montevideo
America/Montreal
America/Montserrat
America/Nassau
America/New_York
America/Nipigon
America/Nome
America/Noronha
America/North_Dakota/Beulah
America/North_Dakota/Center
America/North_Dakota/New_Salem
America/Nuuk
America/Ojinaga
America/Panama
America/Pangnirtung
America/Paramaribo
America/Phoenix
America/Port-au-Prince
America/Port_of_Spain
America/Porto_Acre
America/Porto_Velho
America/Puerto_Rico
America/Punta_Arenas
America/Rainy_River
America/Rankin_Inlet
America/Recife
America/Regina
America/Resolute
America/Rio_Branco
America/Rosario
America/Santa_Isabel
America/Santarem
America/Santiago
America/Santo_Domingo
America/Sao_Paulo
America/Scoresbysund
America/Shiprock
America/Sitka
America/St_Barthelemy
America/St_Johns
America/St_Kitts
America/St_Lucia
America/St_Thomas
America/St_Vincent
America/Swift_Current
America/Tegucigalpa
America/Thule
America/Thunder_Bay
America/Tijuana
America/Toronto
America/Tortola
America/Vancouver
America/Virgin
America/Whitehorse
America/Winnipeg
America/Yakutat
America/Yellowknife
Antarctica/Casey
Antarctica/Davis
Antarctica/DumontDUrville
Antarctica/Macquarie
Antarctica/Mawson
Antarctica/McMurdo
Antarctica/Palmer
Antarctica/Rothera
Antarctica/South_Pole
Antarctica/Syowa
Antarctica/Troll
Antarctica/Vostok
Arctic/Longyearbyen
Asia/Aden
Asia/Almaty
Asia/Amman
Asia/Anadyr
Asia/Aqtau
Asia/Aqtobe
Asia/Ashgabat
Asia/Ashkhabad
Asia/Atyrau
Asia/Baghdad
Asia/Bahrain
Asia/Baku
Asia/Bangkok
Asia/Barnaul
Asia/Beirut
Asia/Bishkek
Asia/Brunei
Asia/Calcutta
Asia/Chita
Asia/Choibalsan
Asia/Chongqing
Asia/Chungking
Asia/Colombo
Asia/Dacca
Asia/Damascus
Asia/Dhaka
Asia/Dili
Asia/Dubai
Asia/Dushanbe
Asia/Famagusta
Asia/Gaza
Asia/Harbin
Asia/Hebron
Asia/Ho_Chi_Minh
Asia/Hong_Kong
Asia/Hovd
Asia/Irkutsk
Asia/Istanbul
Asia/Jakarta
Asia/Jayapura
Asia/Jerusalem
Asia/Kabul
Asia/Kamchatka
Asia/Karachi
Asia/Kashgar
Asia/Kathmandu
Asia/Katmandu
Asia/Khandyga
Asia/Kolkata
Asia/Krasnoyarsk
Asia/Kuala_Lumpur
Asia/Kuching
Asia/Kuwait
Asia/Macao
Asia/Macau
Asia/Magadan
Asia/Makassar
Asia/Manila
Asia/Muscat
Asia/Nicosia
Asia/Novokuznetsk
Asia/Novosibirsk
Asia/Omsk
Asia/Oral
Asia/Phnom_Penh
Asia/Pontianak
Asia/Pyongyang
Asia/Qatar
Asia/Qostanay
Asia/Qyzylorda
Asia/Rangoon
Asia/Riyadh
Asia/Saigon
Asia/Sakhalin
Asia/Samarkand
Asia/Seoul
Asia/Shanghai
Asia/Singapore
Asia/Srednekolymsk
Asia/Taipei
Asia/Tashkent
Asia/Tbilisi
Asia/Tehran
Asia/Tel_Aviv
Asia/Thimbu
Asia/Thimphu
Asia/Tokyo
Asia/Tomsk
Asia/Ujung_Pandang
Asia/Ulaanbaatar
Asia/Ulan_Bator
Asia/Urumqi
Asia/Ust-Nera
Asia/Vientiane
Asia/Vladivostok
Asia/Yakutsk
Asia/Yangon
Asia/Yekaterinburg
Asia/Yerevan
Atlantic/Azores
Atlantic/Bermuda
Atlantic/Canary
Atlantic/Cape_Verde
Atlantic/Faeroe
Atlantic/Faroe
Atlantic/Jan_Mayen
Atlantic/Madeira
Atlantic/Reykjavik
Atlantic/South_Georgia
Atlantic/St_Helena
Atlantic/Stanley
Australia/ACT
Australia/Adelaide
Australia/Brisbane
Australia/Broken_Hill
Australia/Canberra
Australia/Currie
Australia/Darwin
Australia/Eucla
Australia/Hobart
Australia/LHI
Australia/Lindeman
Australia/Lord_Howe
Australia/Melbourne
Australia/NSW
Australia/North
Australia/Perth
Australia/Queensland
Australia/South
Australia/Sydney
Australia/Tasmania
Australia/Victoria
Australia/West
Australia/Yancowinna
Brazil/Acre
Brazil/DeNoronha
Brazil/East
Brazil/West
CET
CST6CDT
Canada/Atlantic
Canada/Central
Canada/Eastern
Canada/Mountain
Canada/Newfoundland
Canada/Pacific
Canada/Saskatchewan
Canada/Yukon
Chile/Continental
Chile/EasterIsland
Cuba
EET
EST
EST5EDT
Egypt
Eire
Etc/GMT
Etc/GMT+0
Etc/GMT+1
Etc/GMT+10
Etc/GMT+11
Etc/GMT+12
Etc/GMT+2
Etc/GMT+3
Etc/GMT+4
Etc/GMT+5
Etc/GMT+6
Etc/GMT+7
Etc/GMT+8
Etc/GMT+9
Etc/GMT-0
Etc/GMT-1
Etc/GMT-10
Etc/GMT-11
Etc/GMT-12
Etc/GMT-13
Etc/GMT-14
Etc/GMT-2
Etc/GMT-3
Etc/GMT-4
Etc/GMT-5
Etc/GMT-6
Etc/GMT-7
Etc/GMT-8
Etc/GMT-9
Etc/GMT0
Etc/Greenwich
Etc/UCT
Etc/UTC
Etc/Universal
Etc/Zulu
Europe/Amsterdam
Europe/Andorra
Europe/Astrakhan
Europe/Athens
Europe/Belfast
Europe/Belgrade
Europe/Berlin
Europe/Bratislava
Europe/Brussels
Europe/Bucharest
Europe/Budapest
Europe/Busingen
Europe/Chisinau
Europe/Copenhagen
Europe/Dublin
Europe/Gibraltar
Europe/Guernsey
Europe/Helsinki
Europe/Isle_of_Man
Europe/Istanbul
Europe/Jersey
Europe/Kaliningrad
Europe/Kiev
Europe/Kirov
Europe/Kyiv
Europe/Lisbon
Europe/Ljubljana
Europe/London
Europe/Luxembourg
Europe/Madrid
Europe/Malta
Europe/Mariehamn
Europe/Minsk
Europe/Monaco
Europe/Moscow
Europe/Nicosia
Europe/Oslo
Europe/Paris
Europe/Podgorica
Europe/Prague
Europe/Riga
Europe/Rome
Europe/Samara
Europe/San_Marino
Europe/Sarajevo
Europe/Saratov
Europe/Simferopol
Europe/Skopje
Europe/Sofia
Europe/Stockholm
Europe/Tallinn
Europe/Tirane
Europe/Tiraspol
Europe/Ulyanovsk
Europe/Uzhgorod
Europe/Vaduz
Europe/Vatican
Europe/Vienna
Europe/Vilnius
Europe/Volgograd
Europe/Warsaw
Europe/Zagreb
Europe/Zaporozhye
Europe/Zurich
GB
GB-Eire
GMT
GMT+0
GMT-0
GMT0
Greenwich
HST
Hongkong
Iceland
Indian/Antananarivo
Indian/Chagos
Indian/Christmas
Indian/Cocos
Indian/Comoro
Indian/Kerguelen
Indian/Mahe
Indian/Maldives
Indian/Mauritius
Indian/Mayotte
Indian/Reunion
Iran
Israel
Jamaica
Japan
Kwajalein
Libya
MET
MST
MST7MDT
Mexico/BajaNorte
Mexico/BajaSur
Mexico/General
NZ
NZ-CHAT
Navajo
PRC
PST8PDT
Pacific/Apia
Pacific/Auckland
Pacific/Bougainville
Pacific/Chatham
Pacific/Chuuk
Pacific/Easter
Pacific/Efate
Pacific/Enderbury
Pacific/Fakaofo
Pacific/Fiji
Pacific/Funafuti
Pacific/Galapagos
Pacific/Gambier
Pacific/Guadalcanal
Pacific/Guam
Pacific/Honolulu
Pacific/Johnston
Pacific/Kanton
Pacific/Kiritimati
Pacific/Kosrae
Pacific/Kwajalein
Pacific/Majuro
Pacific/Marquesas
Pacific/Midway
Pacific/Nauru
Pacific/Niue
Pacific/Norfolk
Pacific/Noumea
Pacific/Pago_Pago
Pacific/Palau
Pacific/Pitcairn
Pacific/Pohnpei
Pacific/Ponape
Pacific/Port_Moresby
Pacific/Rarotonga
Pacific/Saipan
Pacific/Samoa
Pacific/Tahiti
Pacific/Tarawa
Pacific/Tongatapu
Pacific/Truk
Pacific/Wake
Pacific/Wallis
Pacific/Yap
Poland
Portugal
ROC
ROK
Singapore
Turkey
UCT
US/Alaska
US/Aleutian
US/Arizona
US/Central
US/East-Indiana
US/Eastern
US/Hawaii
US/Indiana-Starke
US/Michigan
US/Mountain
US/Pacific
US/Samoa
UTC
Universal
W-SU
WET
Zulu

In [278]:
order_df = order_df.set_index('order_time').sort_index()

In [279]:
order_df.loc['2015']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-20 21:52:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00+09:00
2015-02-07 22:53:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00+09:00
2015-02-08 13:15:00+09:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00+09:00
2015-02-24 03:25:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00+09:00
2015-03-09 03:56:00+09:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00+09:00
2015-03-19 23:11:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,3,2015-03-21 13:25:00+09:00
2015-03-24 10:44:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,5,299.95,2,2015-03-24 12:37:00+09:00
2015-03-26 20:33:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,3,149.94,3,2015-03-28 20:21:00+09:00
2015-04-02 00:02:00+09:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,4,2015-04-08 13:45:00+09:00
2015-04-06 09:09:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,3,2015-04-08 10:59:00+09:00
2015-04-07 00:12:00+09:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,1,50.00,3,2015-04-09 15:28:00+09:00
2015-05-04 02:06:00+09:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-05-08 19:08:00+09:00
2015-05-09 23:17:00+09:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-05-11 10:08:00+09:00
2015-05-14 02:05:00+09:00,Accessories,Team Golf New England Patriots Putter Grip,24.99,5,124.95,6,2015-05-18 10:57:00+09:00
2015-05-17 10:40:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,2,119.98,6,2015-05-21 17:26:00+09:00
2015-05-28 22:02:00+09:00,Shop By Sport,Columbia Men's PFG Anchor Tough T-Shirt,30.00,2,60.00,6,2015-06-02 17:57:00+09:00
2015-05-31 08:53:00+09:00,Shop By Sport,Under Armour Girls' Toddler Spine Surge Runni,39.99,4,159.96,3,2015-06-02 17:51:00+09:00
2015-06-08 21:30:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-10 10:21:00+09:00
2015-06-18 05:43:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-20 14:11:00+09:00
2015-06-21 07:38:00+09:00,Golf Shoes,LIJA Women's Eyelet Sleeveless Golf Polo,65.00,1,65.00,6,2015-06-24 18:28:00+09:00
2015-06-27 00:37:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,4,239.96,2,2015-06-27 17:18:00+09:00
2015-07-05 09:43:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,2,2015-07-05 17:18:00+09:00
2015-07-08 17:57:00+09:00,Water Sports,Pelican Sunstream 100 Kayak,199.99,1,199.99,6,2015-07-10 14:27:00+09:00
2015-07-15 15:40:00+09:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-07-20 15:52:00+09:00
2015-07-23 17:45:00+09:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-07-27 13:05:00+09:00
2015-08-20 09:18:00+09:00,Water Sports,Pelican Sunstream 100 Kayak,199.99,1,199.99,6,2015-08-23 20:03:00+09:00
2015-08-21 19:17:00+09:00,Lacrosse,Under Armour Men's Tech II T-Shirt,24.99,1,24.99,6,2015-08-26 10:01:00+09:00
2015-08-29 03:10:00+09:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,2,2015-08-29 18:57:00+09:00
2015-09-16 04:32:00+09:00,Shop By Sport,Under Armour Girls' Toddler Spine Surge Runni,39.99,3,119.97,6,2015-09-20 14:05:00+09:00
2015-09-25 09:15:00+09:00,Water Sports,Pelican Sunstream 100 Kayak,199.99,1,199.99,6,2015-09-29 20:18:00+09:00
2015-10-11 14:29:00+09:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,4,2015-10-16 14:15:00+09:00
2015-10-19 10:37:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-10-21 15:46:00+09:00
2015-10-24 06:56:00+09:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,3,2015-10-26 17:44:00+09:00
2015-10-26 03:47:00+09:00,Shop By Sport,Under Armour Girls' Toddler Spine Surge Runni,39.99,3,119.97,6,2015-10-28 16:07:00+09:00
2015-10-28 18:08:00+09:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,6,2015-11-02 16:48:00+09:00
2015-10-31 04:39:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,4,239.96,6,2015-11-02 11:49:00+09:00
2015-11-19 11:06:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,1,49.98,6,2015-11-21 20:33:00+09:00
2015-12-09 01:58:00+09:00,Golf Gloves,Bag Boy Beverage Holder,24.99,5,124.95,3,2015-12-11 20:37:00+09:00
2015-12-09 09:40:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-12-12 15:32:00+09:00
2015-12-16 05:59:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,2,2015-12-16 16:55:00+09:00
2015-12-23 11:24:00+09:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,6,2015-12-25 11:04:00+09:00
2015-12-29 08:57:00+09:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,1,99.99,6,2016-01-04 14:19:00+09:00
2015-12-31 02:38:00+09:00,Girls' Apparel,adidas Men's Germany Black Crest Away Tee,25.00,3,75.00,6,2016-01-05 11:21:00+09:00

In [280]:
order_df.loc['2015-06']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-06-08 21:30:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-10 10:21:00+09:00
2015-06-18 05:43:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-20 14:11:00+09:00
2015-06-21 07:38:00+09:00,Golf Shoes,LIJA Women's Eyelet Sleeveless Golf Polo,65.00,1,65.00,6,2015-06-24 18:28:00+09:00
2015-06-27 00:37:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,4,239.96,2,2015-06-27 17:18:00+09:00

In [281]:
order_df.loc['2015-06-18']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-06-18 05:43:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-20 14:11:00+09:00

In [282]:
order_df.loc['2015' : '2017']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-20 21:52:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,5,249.90,6,2015-01-26 15:42:00+09:00
2015-02-07 22:53:00+09:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,2,99.96,6,2015-02-09 12:33:00+09:00
2015-02-08 13:15:00+09:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,3,2015-02-10 10:29:00+09:00
2015-02-24 03:25:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-03-02 16:14:00+09:00
2015-03-09 03:56:00+09:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,6,2015-03-12 14:59:00+09:00
...,...,...,...,...,...,...,...
2017-08-01 03:45:00+09:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,1,59.99,6,2017-08-03 16:35:00+09:00
2017-08-02 05:20:00+09:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2017-08-07 10:27:00+09:00
2017-09-13 21:23:00+09:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,2,2017-09-14 20:43:00+09:00
2017-10-11 14:20:00+09:00,Cameras,Web Camera,452.04,1,452.04,2,2017-10-12 20:48:00+09:00
2017-10-19 15:23:00+09:00,Children's Clothing,Children's heaters,357.10,1,357.10,6,2017-10-21 14:16:00+09:00


## 주문 후 배송 시간 확인하기

In [283]:
import pandas as pd

order_df = pd.read_csv('data/order.csv')
order_df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaN,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [284]:
order_df['order_time'] = pd.to_datetime(order_df['order_time'])
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'])

In [285]:
order_df.dtypes

order_time                     datetime64[us]
category                                  str
product_name                              str
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[us]
dtype: object

In [290]:
order_df= order_df.set_index('order_time').sort_index()

In [291]:
order_df['shipping_time'] - order_df.index

order_time
2015-01-01 02:27:00   4 days 10:48:00
2015-01-01 03:51:00   3 days 16:15:00
2015-01-01 04:33:00   5 days 13:28:00
2015-01-01 04:54:00   6 days 14:13:00
2015-01-01 07:42:00   4 days 09:23:00
                            ...
2018-01-31 16:59:00   6 days 03:33:00
2018-01-31 17:20:00   1 days 16:56:00
2018-01-31 18:44:00   6 days 00:09:00
2018-01-31 21:53:00   1 days 20:57:00
NaT                               NaT
Length: 18050, dtype: timedelta64[us]

In [293]:
order_df['days_for_shipping(actual)'] = order_df['shipping_time'] - order_df.index

In [294]:
order_df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual)
order_time,,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00,4 days 10:48:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00,3 days 16:15:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00,5 days 13:28:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00,6 days 14:13:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00,4 days 09:23:00
...,...,...,...,...,...,...,...,...
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00,6 days 03:33:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00,1 days 16:56:00
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 18:53:00,6 days 00:09:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00,1 days 20:57:00
NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00,NaT

In [295]:
order_df.dtypes

category                                   str
product_name                               str
price                                  float64
quantity                                 int64
sales                                  float64
days_for_shipping(expected)              int64
shipping_time                   datetime64[us]
days_for_shipping(actual)      timedelta64[us]
dtype: object

In [296]:
pd.to_timedelta(order_df['days_for_shipping(expected)'], unit='D')

order_time
2015-01-01 02:27:00   6 days
2015-01-01 03:51:00   6 days
2015-01-01 04:33:00   6 days
2015-01-01 04:54:00   6 days
2015-01-01 07:42:00   4 days
                       ...
2018-01-31 16:59:00   6 days
2018-01-31 17:20:00   6 days
2018-01-31 18:44:00   6 days
2018-01-31 21:53:00   3 days
NaT                   6 days
Name: days_for_shipping(expected), Length: 18050, dtype: timedelta64[s]

In [297]:
order_df['days_for_shipping(expected)'] = pd.to_timedelta(order_df['days_for_shipping(expected)'], unit='D')

In [298]:
order_df.dtypes

category                                   str
product_name                               str
price                                  float64
quantity                                 int64
sales                                  float64
days_for_shipping(expected)     timedelta64[s]
shipping_time                   datetime64[us]
days_for_shipping(actual)      timedelta64[us]
dtype: object

In [299]:
order_df['days_for_shipping(expected)'] < order_df['days_for_shipping(actual)']  # True 오래걸림, False 제때 옴

order_time
2015-01-01 02:27:00    False
2015-01-01 03:51:00    False
2015-01-01 04:33:00    False
2015-01-01 04:54:00     True
2015-01-01 07:42:00     True
                       ...
2018-01-31 16:59:00     True
2018-01-31 17:20:00    False
2018-01-31 18:44:00     True
2018-01-31 21:53:00    False
NaT                    False
Length: 18050, dtype: bool

In [300]:
order_df['late_shipping'] = order_df['days_for_shipping(expected)'] < order_df['days_for_shipping(actual)']
order_df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
order_time,,,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6 days,2015-01-05 13:15:00,4 days 10:48:00,False
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6 days,2015-01-04 20:06:00,3 days 16:15:00,False
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6 days,2015-01-06 18:01:00,5 days 13:28:00,False
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4 days,2015-01-05 17:05:00,4 days 09:23:00,True
...,...,...,...,...,...,...,...,...,...
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 20:32:00,6 days 03:33:00,True
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-02 10:16:00,1 days 16:56:00,False
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 18:53:00,6 days 00:09:00,True
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3 days,2018-02-02 18:50:00,1 days 20:57:00,False
NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6 days,2015-01-04 09:47:00,NaT,False

In [301]:
order_df['late_shipping'].value_counts()

late_shipping
False    14846
True      3204
Name: count, dtype: int64

In [ ]:
order_df[order_df['late_shipping']]  # 배송지연자들 할인쿠폰 발행하면 좋을 듯

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
order_time,,,,,,,,,
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4 days,2015-01-05 17:05:00,4 days 09:23:00,True
2015-01-01 08:03:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,4 days,2015-01-06 12:32:00,5 days 04:29:00,True
2015-01-01 12:57:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-05 15:14:00,4 days 02:17:00,True
2015-01-02 05:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-07 12:48:00,5 days 07:44:00,True
...,...,...,...,...,...,...,...,...,...
2018-01-28 20:40:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-03 09:15:00,5 days 12:35:00,True
2018-01-29 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-04 16:17:00,6 days 03:51:00,True
2018-01-29 14:11:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-04 20:04:00,6 days 05:53:00,True
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 20:32:00,6 days 03:33:00,True
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 18:53:00,6 days 00:09:00,True